services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    hostname: mongodb
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_DB_USER:-user}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD:-password}
    ports:
      - ${MONGO_DB_PORT:-27017}:27017
    volumes:
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot
      - ./init:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    container_name: nba_fantastic_redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD:-my_secure_password} --appendonly yes
    restart: unless-stopped
  api:
    build:
      context: .
      target: development
    container_name: nba_api_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://nba_fantastic:superpasswordfornbafantastic@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
volumes:
  db:
  configdb:
  mongot:
