[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "juanzeen", email = "jziignerdev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "httpx2>=2.12.0",
    "nba-api>=1.11.4",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pymongo>=4.17.0",
    "pytest>=9.1.1",
]

[project.scripts]
app = "app:main"

[tool.fastapi]
entrypoint = "src.app.main:app"


[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
